apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: membership
type: Opaque
stringData:
  MARIADB_DATABASE: membership
  MARIADB_USER: membership_user
  MARIADB_PASSWORD: membership_password
  MARIADB_ROOT_PASSWORD: root_password

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: membership
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: membership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb

    spec:
      containers:
        - name: mariadb
          image: mariadb:lts

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: mariadb-secret

          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: membership
spec:
  selector:
    app: mariadb

  ports:
    - port: 3306
      targetPort: 3306

  type: ClusterIP