apiVersion: v1
kind: Secret

metadata:
  name: {{ include "membership-api-chart.fullname" . }}-secret
  labels:
    {{- include "membership-api-chart.labels" . | nindent 4 }}

type: Opaque

stringData:
  DB_USER: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}